
import { golos } from '@/shared/assets/fonts/fonts'

import type { Metadata } from 'next'

import './globals.css'

export const metadata: Metadata = {
  title: 'Space',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={golos.className}>
        {children}
      </body>
    </html>
  )
}
